Cleaned up konsole install script

diff --git a/install/konsole b/install/konsole
--- a/install/konsole
+++ b/install/konsole
@@ -1,37 +1,82 @@
 #!/usr/bin/env bash
 
-function install_package() {
-	package=$1; shift
-	message=$1
+declare -A applications
 
-	if which paru &> /dev/null; then
+function boolean() {
+    if $@; then
+        printf "true\n"
+    else
+        printf "false\n"
+    fi
+}
+
+function printf_if() {
+    local enable=$1; shift
+    if $enable; then
+        printf "$@"
+    fi
+}
+
+function check_application() {
+    local application=$1
+
+    if [[ -z ${application[$application]} ]]; then
+        if which $application &> /dev/null; then
+            applications[$application]=true
+        else
+            applications[$application]=false
+        fi
+    fi
+    ${applications[$application]}
+    return $?
+}
+
+function quit() {
+    unset applications
+    exit $1
+}
+
+function install_package() {
+    local package=$1; shift
+	local name=$1
+
+    if check_application paru; then
 		if ! paru -Qs "^$package\$" &> /dev/null; then
-			if [[ -n $message ]]; then echo -e "\e[34m$message\e[0m"; fi
+			printf_if $(boolean test -n $name) "\e[2mInstalling package $name...\e[0m "
 			paru -S --noconfirm $package &> /dev/null
+            printf_if $(boolean test -n $name) "\e[32mInstalled\e[0m\n"
 		fi
+        return 0
 	else
-		echo -e '\e[31merror: paru is not installed.\e[0m'
-		echo -e '\e[3mGo to https://github.com/Morganamilo/paru for instructions.\e[0m'
-		exit 1
+	    printf "\e[31merror: paru is not available.\e[0m\n"
+		printf "\e[3mGo to https://github.com/Morganamilo/paru for installation instructions.\e[0m\n"
+		return 1
 	fi
 }
 
 function install_dotfile() {
-	source=$1; shift
-	destination=$1; shift
-	message=$1
+	local source=$1; shift
+	local destination=$1; shift
+	local message=$1
+
+    if ! check_application rm || ! check_application ln; then
+        printf "\e[31merror: rm and/or ln is not available.\e[0m\n"
+        printf "\e[3mAre you running this on an Arch Linux system?\e[0m\n"
+        return 1
+    fi
 
 	if [[ ! -h $destination ]]; then
-		if [[ -n $message ]]; then echo -e "\e[36m\e[1m$message\e[0m"; fi
-		if [[ -e $destination ]]; then rm $destination; fi
+		printf_if $(boolean test -n $message) "\e[2m$message\e[0m"; fi
+		if [[ -e $destination ]]; then
+            rm $destination;
+        fi
 		ln -s $source $destination
 	fi
 }
 
-install_package konsole 'Installing Konsole...'
-install_package powerline 'Installing powerline...'
-install_package 3270-fonts 'Installing IBM 3270 fonts...'
+install_package konsole "Konsole" && \
+install_package powerline "Powerline" && \
+install_package 3270-fonts "IBM 3270 fonts" && \
 install_dotfile $HOME/.konsole/konsolerc $HOME/.config/konsolerc 'Installing Konsole general configuration...'
-install_dotfile $HOME/.konsole/konsoleui.rc $HOME/.local/share/kxmlgui5/konsole/konsoleui.rc 'Installing Konsole keyboard shortcuts and toolbar configuration...'
 install_dotfile $HOME/.konsole/Oldschool.profile $HOME/.local/share/konsole/Oldschool.profile 'Installing Konsole profile...'
 install_dotfile $HOME/.konsole/Pure.colorscheme $HOME/.local/share/konsole/Pure.colorscheme 'Installing Konsole color scheme...'
